### ISSUE TITLE
update README.md for clarification about status?

### ISSUE THREAD

**Issue by daringer** [Nitrokey/nitro-python#3]
Hey hey,

recently got a *Nitrokey FIDO2*, eager to get lower level/devel access to the device I found this project, which caught my attention with the sub-title: **Python client for Nitrokey FIDO2, based on Solo**

Scrolled through the README and was triggered by "update firmware", instantly running:
```bash
solo key update
```
left me with the **key stuck in bootloader-mode**, as the command still tries to flash the solo firmware instead of the correct Nitrokey firmware. 

-------------------
As a micro documentation (btw. haven't found any for flashing), if someone is falling into the same hole **How to flash Nitrokey FIDO2 firmware**, my steps to *revive* the key:
* Make sure you have `solo` from this repo installed
* Stuck in bootloader? You should be able to read the bootloader version:
```bash
solo program aux bootloader-version
```
* If this fails, you might **not** be stuck in bootloader-mode (check LEDs). 
Additionally, you can manually enter the bootloader
```bash
solo program aux enter-bootloader
```
* Do not forget to **confirm using the touch sensor**, LEDs should now have changed to pulsing, purple (`dmesg` will show either `Nitrokey FIDO2` or `Nitrokey FIDO2 Bootloader`)
* Now to flash the firmware: (bootloader 1.1, using (signed) firmware 1.1)
```bash
wget https://github.com/Nitrokey/nitrokey-fido2-firmware/releases/download/1.1.0.nitrokey/fido2-firmware-1.1.0.nitrokey-app-signed.json
# and program it through the bootloader:
solo program bootloader fido2-firmware-1.1.0.nitrokey-app-signed.json
```
* The stick **will not** reboot itself, be sure that you see "...pass" after programming, finally to reboot into the application:
```bash
solo program aux leave-bootloader
```
-------------------

@szszszsz hope it's ok that I am abusing this issue for documentation. Had a strong urge to write this down and make it available to hopefully safe others from the same pity. Did I maybe oversee some documentation for all this?

Apart from this, as the issue title suggests: how do you think about an update for the `README.md` to clarify what to expect from this project in this state, what's working and not using this tool. I could put some lines together and PR it if you'd like?

**Comment by szszszsz** [comment]
Hi @daringer!

Sorry for the late reply, and the confusion made because of missing warning about being it a work in progress. I have corrected that with the latest release. 

The automatic firmware update is disabled for now, as I have not found time yet to test it. We plan to use browser based update instead as the main method - more in the project's readme file.
Your steps for reviving the device were right, and I have added them to the documentation, thank you! If you feel it misses any other detail feel free to make PRs or tickets, all contributions are welcome! On any bigger improvements we plan to push the changes to the upstream, to keep in sync.
